name: Deploy Vue App to EC2 Docker Container

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20.19.0'

      - name: Install & Build Vue Project
        run: |
          npm install
          npm run build

      - name: Decode SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" | base64 --decode > private_key.pem
          chmod 600 private_key.pem

      - name: Transfer dist contents to EC2:/home/ubuntu/vue/
        run: |
          scp -i private_key.pem -o StrictHostKeyChecking=no -r dist/* \
          ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ubuntu/vue/
